config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  resources :usersessions, except: [:new, :destroy]
  resources :users
  resources :posts do
    resources :comments
  end
  post 'comment_search' => 'comments#dashboard', as: :comment_search
  post 'post_search' => 'posts#dashboard', as: :post_search
  post 'user_search' => 'users#dashboard', as: :user_search
  get 'login' => 'usersessions#new', as: :login
  post 'logout' => 'usersessions#destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, :text, presence: true, uniqueness: true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create },
                    uniqueness: { case_sensitive: false }
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login
  before_action :set_comment, except: :dashboard

  def dashboard
    @search = Comment.search(params[:q])
    @searched_comments = @search.result
  end

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    render 'new' unless @comment.save
  end

  def update
    @comment.update(comment_params)
    render 'edit' unless @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Comment was deleted' if current_user.admin }
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_comment
    @post = Post.find(params[:post_id]) if params[:post_id]
    @comment = @post.comments.find(params[:id]) if params[:id]
    @comments = @post.comments.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @data = { email: current_user.email, posts: current_user.posts.count, comments: current_user.comments.count, admin: current_user.admin } if current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  before_action :set_post, except: :dashboard

  def dashboard
    @search = Post.search(params[:q])
    @searched_posts = @search.result
  end

  def index
    @posts = Post.paginate(page: params[:page], per_page: 3)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @comments = @post.comments.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit; end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    render 'new' unless @post.save
  end

  def update
    @post.update(post_params)
    render 'edit' unless @post.update(post_params)
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was deleted' if current_user.admin }
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:name, :text)
  end

  def set_post
    @post = Post.find(params[:id]) if params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  def dashboard
    @search = User.search(params[:q])
    @searched_users = @search.result
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(user_params[:email], user_params[:password])
      redirect_to root_path, notice: 'Succesfully registered'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Profile was changed'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'User was deleted'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/usersessions_controller.rb
class UsersessionsController < ApplicationController
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to root_path, notice: 'Succesfully logined'
    else
      flash.now[:alert] = "Can't login"
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logout'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48&d=#{CGI.escape('')}"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def sanitz(post)
    sanitize post.text, tags: %w(a b i strong em p h1 h2 h3 h4 h5 h6 br hr ul li img pre blockquote), attributes: %w(href name src type value width height style)
  end

  def commts(post)
    post.comments.count
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def number_posts(user)
    user.posts.count
  end

  def number_comments(user)
    user.comments.count
  end
end

app/helpers/usersessions_helper.rb
module UsersessionsHelper
end

app/views/comments/_comment.html.slim
.item[data-item-id="#{comment.id}"]
  #text
    = image_tag avatar_url(comment.user), style: 'border-radius: 50%;'
    =< comment.text
    br/
    | Author: #{comment.user.email}
    |  Created: #{comment.created_at}
    p
      br/
      - if comment.user == current_user || current_user.admin
        =< link_to 'Edit comment', edit_post_comment_path(@post, comment), class: 'btn btn-primary', remote: true
        =< link_to 'Delete comment', post_comment_path(@post, comment), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary', remote: true

app/views/comments/_form.html.slim
= simple_form_for [@post, @comment], remote: true do |form|
  = form.input :text, as: :text, input_html: {rows: '4'}, required: true 
  = form.button :submit, class: 'btn btn-primary'

app/views/comments/create.js.erb
$('#comment-close').hide();
$('#form-comment').fadeOut();
$('#comments').append("<%= j render @comment %>");

app/views/comments/dashboard.html.slim
h4
  | Administrators table of comments
br/
= search_form_for @search, url: comment_search_path, method: :post do |f|
  .field
    =< f.label :text_cont, 'Text contains'
    =< f.text_field :text_cont         
    =< f.submit "Search"
table#table
  tr
    th
      | Post name
    th
      | Comment author
    th
      | Comment text
    th
      | Created
    th
      | Updated
    th
      | Actions
  - @searched_comments.each do |comment|
    tr
      td
        = link_to(comment.post.name, comment.post)
      td
        = comment.user.email
      td
        = comment.text
      td
        = comment.created_at
      td
        = comment.updated_at
      td
        = link_to 'Delete', post_comment_path(comment.post, comment), method: :delete, data: {confirm: 'Are you sure?'}     

app/views/comments/destroy.js.erb
$('.item[data-item-id=<%= @comment.id %>]').remove();

app/views/comments/edit.html.slim
h3 Edit comment
= render 'form'

app/views/comments/edit.js.erb
$('#form-comment').html("<%= j render 'form' %>");
$('#form-comment').fadeIn();
$('#comment-close').show();
$("textarea").focus();
$("body, html").animate({scrollTop: $(document).height()}, 400) 

app/views/comments/new.html.slim
h3 New comment
= render 'form'

app/views/comments/new.js.erb
$('#form-comment').html("<%= j render 'form' %>");
$('#form-comment').fadeIn();
$('#comment-close').show();
$("textarea").focus();
$("body, html").animate({scrollTop: $(document).height()}, 400);

app/views/comments/update.js.erb
$('#comment-close').hide();
$('#form-comment').fadeOut();
$('.item[data-item-id=<%= @comment.id %>]').replaceWith("<%= j render @comment %>");

app/views/home/welcome.html.slim
- if current_user
  h3 Hello, #{@data[:email]}
  = image_tag avatar_url(current_user)
  hr/
  p
    | You have #{@data[:posts]} posts.
  p
    | You have #{@data[:comments]} comments. 
  - if current_user.admin
    h4 Welcome, administrator.
    =< link_to 'Table of posts', post_search_path, method: :post, class: 'btn btn-primary'
    =< link_to 'Table of comments', comment_search_path, method: :post, class: 'btn btn-primary'  
    =< link_to 'Table of users', user_search_path, method: :post, class: 'btn btn-primary'    
  =< link_to 'Edit profile', edit_user_path(current_user.id), class: 'btn btn-primary'
  =< link_to 'Logout', logout_path, method: :post, class: 'btn btn-primary'
  =< link_to 'All posts', posts_path, class: 'btn btn-primary'    
- else  
  h2 You must register or login to continue.

app/views/layouts/application.html.erb
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Forum
    = csrf_meta_tags    
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    .container
      p.notice= notice
      p.alert= alert
      = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Forum
    = csrf_meta_tags    
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    .container
      - if current_user
        = image_tag avatar_url(current_user), style: 'border-radius: 50%;'
        =<> current_user.email
        =< link_to 'Home', root_path
        =< link_to 'Edit profile', edit_user_path(current_user.id)
        =< link_to 'Logout', logout_path, method: :post
        =< link_to 'All posts', posts_path
        - if current_user.admin       
          =< link_to 'Table of posts', post_search_path, method: :post
          =< link_to 'Table of comments', comment_search_path, method: :post
          =< link_to 'Table of users', user_search_path, method: :post
      - else
        = link_to 'Registration', new_user_path
        =< link_to 'Sign in', login_path 
      p.notice= notice
      p.alert= alert
      = yield

app/views/posts/_form.html.slim
br/
= simple_form_for @post, remote: true do |form|
  = form.input :name, as: :text, input_html: { style: 'height:35px;' }, required: true
  = form.input :text, as: :text, input_html: { rows: 7 }
  br/
  = form.button :submit, class: 'btn btn-primary'

app/views/posts/_post.html.slim
- sho = request.original_url.include?("posts/")
.item[data-item-id="#{post.id}"]
  #text
    = image_tag avatar_url(post.user), style: 'border-radius: 50%;'
    h3 =post.name
    = sanitz (post) if sho
    hr/
    | Author: #{post.user.email}
    |  Created: #{post.created_at}
    p
      br/
      =< link_to 'Show', post_path(post), class: 'btn btn-primary' unless sho
      - if post.user == current_user || current_user.admin
        =< link_to 'Edit', edit_post_path(post), class: 'btn btn-primary', remote: true if sho
        =< link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary', remote: true unless sho

app/views/posts/create.js.erb
$('#close').hide();
$('#form').fadeOut();
if ($('.item').length != 3) {
 $('#posts').append("<%= j render @post %>");
}
 else {
  location.reload();
 }

app/views/posts/dashboard.html.slim
h4
  | Administrators table of posts
br/
= search_form_for @search, url: post_search_path, method: :post do |f|
  .field
    = f.label :name_cont, 'Name contains'
    =< f.text_field :name_cont
    =< f.label :text_cont, 'Text contains'
    =< f.text_field :text_cont         
    =< f.submit "Search"
table#table
  tr
    th
      | Post name
    th
      | Post author
    th
      | Post text
    th
      | Created
    th
      | Updated
    th
      | Comments
    th
      | Actions
  - @searched_posts.each do |post|
    tr
      td
        = link_to(post.name, post)
      td
        = post.user.email
      td
        = sanitz(post)
      td
        = post.created_at
      td
        = post.updated_at
      td
        = commts(post)
      td        
        = link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'}

app/views/posts/destroy.js.erb
$('.item[data-item-id=<%= @post.id %>]').remove();

app/views/posts/edit.html.slim
h3 Edit post
= render 'form'

app/views/posts/edit.js.erb
$('#form').html("<%= j render 'form' %>");
$('#form').fadeIn();
$('#close').show();
$("textarea").focus();
$("body, html").animate({scrollTop: $(document).height()}, 400) 

app/views/posts/index.html.slim
h2 All posts
#posts
  = render @posts
= will_paginate @posts, renderer: BootstrapPagination::Rails
h2  
  => link_to 'New post', new_post_path, remote: true, class: 'btn btn-primary' if @posts.total_pages == @posts.current_page
  = link_to 'Close form', '#', id: 'close', class: 'btn btn-primary'
#form

app/views/posts/new.html.slim
h3 New post
= render 'form'

app/views/posts/new.js.erb
$('#form').html("<%= j render 'form' %>");
$('#form').fadeIn();
$('#close').show();
$("textarea").focus();
$("body, html").animate({scrollTop: $(document).height()}, 400);

app/views/posts/show.html.slim
#posts-show
 = render @post
= link_to 'Close form', '#', id: 'close', class: 'btn btn-primary'
#form    
#comments
  = render @comments
h2 
  => link_to 'New comment', new_post_comment_path(@post), remote: true, class: 'btn btn-primary'
  = link_to 'Close comment form', '#', id: 'comment-close', class: 'btn btn-primary'
#form-comment

app/views/posts/update.js.erb
$('#close').hide();
$('#form').fadeOut();
$('#posts-show').replaceWith("<%= j render @post %>");

app/views/users/dashboard.html.slim
h4
  | Administrators table of users
br/
= search_form_for @search, url: user_search_path, method: :post do |f|
  .field
    = f.label :email_cont, 'Email contains'
    =< f.text_field :email_cont      
    =< f.submit "Search"
table#table
  tr
    th
      | User email
    th
      | Created
    th
      | Updated
    th
      | Posts
    th
      | Comments
    th
      | Actions
  - @searched_users.each do |user|
    tr
      td
        = user.email
      td
        = user.created_at
      td
        = user.updated_at
      td
        = number_posts(user)
      td
        = number_comments(user)
      td        
        = link_to 'Delete', user_path(user), method: :delete, data: {confirm: 'Are you sure?'}

app/views/users/edit.html.slim
h3 Edit_profile
= simple_form_for(@user) do |f|
  = f.error_notification
  .form-inputs
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
  .form-actions
    = f.button :submit, 'Update user', class: "btn btn-primary"
= link_to 'Back', root_path

app/views/users/new.html.slim
h3 Registration
= simple_form_for @user do |f|
  = f.error_notification
  .form-inputs
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
  .form-actions
    = f.button :submit, 'Create user', class: "btn btn-primary"
= link_to 'Back', root_path

app/views/usersessions/new.html.slim
= form_tag usersessions_path, method: :post do
  .form-inputs
    = label_tag :email
    br
    = text_field_tag :email, nil, class: "form-control"
  .form-inputs
    = label_tag :password
    br
    = password_field_tag :password, nil, class: "form-control"
  br
  .form-actions
    = submit_tag 'Login', class: "btn btn-primary"